# Generated by Django 3.0.8 on 2020-07-15 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
